'use strict';

module.exports = Object.freeze({
    booksData: [
        {
          title: 'Godan',
          author: 'Prem Chand',
          isbn: 312,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Harvest',
          author: 'Manjula Padmanabhan',
          isbn: 643122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Heir Apparent',
          author: 'Dr. Karan Singh',
          isbn: 223122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'My Life and Times ',
          author: '	V.V. Giri',
          isbn: 3122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Last Burden ',
          author: 'Upamanyu Chatterjee',
          isbn: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Ram Charita Manas ',
          author: 'Tulsidas',
          isbn: 32,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Ratnavali ',
          author: 'Harsha Vardhan',
          isbn: 122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Sunny Days',
          author: 'Sunny Days',
          isbn: 31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Sultry Days',
          author: 'Shobha De',
          isbn: 313422,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Vikram Seth ',
          author: 'uldeep Nayar',
          isbn: 3173422,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'The Songs of India ',
          author: 'Sarojini Naidu',
          isbn: 322122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'The God of Small Things ',
          author: 'Arundhati Roy',
          isbn: 31745722,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'The Glass Palace ',
          author: 'Amitav Ghosh',
          isbn: 312752,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Yama',
          author: 'Mahadevi Verma',
          isbn: 31523522,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Yashodhara',
          author: 'Maithili Sharan Gupt',
          isbn: 63463122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Years of Pilgrimage',
          author: 'Dr. Raja Ramanna',
          isbn: 64363122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Glimpses of World History',
          author: 'Jawaharlal Nehru',
          isbn: 5233122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'A River Sutra ',
          author: 'Gita Mehta',
          isbn: 37243122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'A House for Mr. Biswas ',
          author: '	V.S. Naipaul',
          isbn: 52353122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Revolution 2020',
          author: 'Chetan Bhagat',
          isbn: 7453122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'A Brush with Life ',
          author: 'Satish Gujral',
          isbn: 623122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'An Idealist View of Life ',
          author: 'Dr. S. Radhakrishnan',
          isbn: 35345122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'An Autobiography',
          author: 'Jawaharlal Nehru',
          isbn: 53453122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Chitra',
          author: 'Rabindranath Tagore',
          isbn: 53453122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'The Bread, Beauty and Revolution ',
          author: 'Khwaja Ahmad Abbas',
          isbn: 83122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Dynamics of Social Change ',
          author: 'Chandra Shekhar',
          isbn: 73122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Devdas',
          author: 'Sarat Chandra Chatterjee',
          isbn: 63122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Days of My Years ',
          author: 'H.P. Nanda',
          isbn: 233122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'I follow the Mahatma',
          author: 'K.M. Munshi',
          isbn: 634643122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Interpreter of Maladies',
          author: 'Jhumpa Lahiri',
          isbn: 23733122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Kagaz Te Canwas ',
          author: '',
          isbn: 63463122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Amrita Pritam',
          author: 'Ginu Kamani',
          isbn: 1253122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Junglee Girl',
          author: 'Ginu Kamani',
          isbn: 315122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Kashmir: A Tale of Shame ',
          author: 'Hari Jaisingh',
          isbn: 3125132,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Kashmir: A Tragedy of Errors',
          author: '	Tavleen Singh',
          isbn: 3511212,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Lipika',
          author: 'Rabindranath Tagore',
          isbn: 31412422,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
    ]
});